sudo: required
language: c
os:
- linux

before_install:
- sudo apt update && sudo apt install curl
- git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 $HOME/arm-eabi-4.8

script:
- ./build.sh

after_success:
- cd out/arch/arm/boot
- zip -r Q372.zip zImage
- curl --upload-file Q372.zip https://transfer.sh
