include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"ili9806e_fwvga_dsi_vdo_tcl")
obj-y   +=  ili9806e_fwvga_dsi_vdo_tcl.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm8019a_fwvga_dsi_vdo_boe")
obj-y   +=  otm8019a_fwvga_dsi_vdo_boe.o
endif


